<div class="points-breakdown-wrapper information">
  <h3>
    <a data-toggle="collapse" data-target="#points-breakdown-list">
      <div class="icon">
        <div class="one"></div>
        <div class="two"></div>
      </div>
      Points Breakdown</a></h3>
  <div id="points-breakdown-list"
       class="collapse">
    <ul>
      <li>Wins (<strong>W</strong>) - <strong>3 points</strong></li>
      <li>OT/SO Wins (<strong>OTW</strong>) - <strong>2
          points</strong></li>
      <li>OT/SO Losses (<strong>OTL</strong>) - <strong>1
          point</strong></li>
      <li>Losses (<strong>L</strong>) - <strong>0 points</strong></li>
    </ul>
  </div>
</div>