<div class="tie-breaker-wrapper">
  <h3>
    <a data-toggle="collapse" data-target="#tie-breaker-list">
      <div class="icon">
        <div class="one"></div>
        <div class="two"></div>
      </div>
      Tie-Breaking Procedure</a></h3>
  <div id="tie-breaker-list"
       class="collapse">
    <ol>
      <li>Wins</li>
      <li>Overtime Wins</li>
      <li>I don't know! This is all hypothetical. If you have a suggestion,
        <a href="https://twitter.com/Thejacer87" target="_blank">send me a
          tweet</a>,
        or create an issue on
        <a href="https://github.com/thejacer87/nhl321/issues" target="_blank">GitHub</a>.
      </li>
    </ol>
  </div>
</div>