<div class="row">
  <div class="col-sm-8 col-xs-12">
    <ul class="nav nav-pills">
      <li class="active"><a data-toggle="tab" href="#wildcard">Wild Card</a>
      </li>
      <li><a data-toggle="tab" href="#division">Division</a></li>
      <li><a data-toggle="tab" href="#conference">Conference</a></li>
      <li><a data-toggle="tab" href="#overall">Overall</a></li>
    </ul>
  </div>
  <div class="col-sm-4 col-xs-4">
    <select class="form-control col-md-2" name="season" id="season">
      <option value="2015">2015/16</option>
      <option value="2016" selected="selected">2016/17</option>
    </select>
  </div>
</div>
<div class="tab-content">
